import img_Product from "../Image/controls/imgProduct.png";
import img_Client from "../Image/controls/imgClient.png";
import img_Avatar from "../Image/controls/imgAvatar.png";
import img_Store from "../Image/controls/imgStore.png";
import img_Reports from "../Image/controls/imgReports.png";
import img_Printer from "../Image/controls/imgPrinter.png";
import img_PDF from "../Image/controls/imgPDF.png";
import img_Facebook from "../Image/controls/imgFacebook.png";
import img_Instagram from "../Image/controls/imgInstagram.png";
import img_Whatsaap from "../Image/controls/imgWatssap.png";
import img_Email from "../Image/controls/imgEmail.png";
import img_Twitter from "../Image/controls/imgTwitter.png";
import img_Linkedin from "../Image/controls/imgLinkedin.png";
import img_Browser from "../Image/controls/imgBrowser.png";

export const imgProduct = img_Product;
export const imgClient = img_Client;
export const imgAvatar = img_Avatar;
export const imgStore = img_Store;
export const imgReports = img_Reports;
export const imgPrinter = img_Printer;
export const imgFacebook = img_Facebook;
export const imgInstagram = img_Instagram;
export const imgWhatsaap = img_Whatsaap;
export const imgEmail = img_Email;
export const imgBrowser = img_Browser;
export const imgTwitter = img_Twitter;
export const imgLinkedin = img_Linkedin;
export const imgPDF = img_PDF;
